### PR TITLE
[DEV][BACKEND] Create default post template for every new community #101

### PR DESCRIPTION
**Pull request by Ozmus**
Default template is created for each new organization

### CODE REVIEW

**Review by CankutER — COMMENTED** [review]
Seems fine. Creating a template with field "Comment", having a String type.

**Comment by niloaydin** [comment]
@Ozmus So in default template we only have one attribute which is comment?

**Comment by Ozmus** [comment]
> @Ozmus So in default template we only have one attribute which is comment?

Yes and there is a name of the template as Default Template

**Comment by niloaydin** [comment]
@AhmetZ06 I think there should be a title and description, because most of the default templates are like that

**Comment by Ozmus** [comment]
> @AhmetZ06 I think there should be a title and description, because most of the default templates are like that

Sure. The title is added

**Review by niloaydin — APPROVED** [review]

**Pull request merged**
